fix(chart): detect safe mounted behavior
Error: mount_linux.go:274 Cannot create temp dir to detect safe 'not mounted' behavior: mkdir /tmp/kubelet-detect-safe-umount1647621063: read-only file system

mount_linux.go requires writable /tmp

Signed-off-by: Serge Logvinov <serge.logvinov@sinextra.dev>